import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { CartProvider } from "./context/CardContext";
import { Toaster } from "react-hot-toast";
import { ClerkProvider, SignedOut, SignIn, UserButton} from "@clerk/nextjs";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
        <ClerkProvider>
      <html lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          <header className="flex justify-between p-2 font-semibold">
            <h1>
            KU KHUY
            </h1>
            <UserButton showName />
          </header>
          <CartProvider>
            <Toaster position="top-right" />
            {children}
          </CartProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
